import jsPDF from 'jspdf';

export type ReportData = {
  phishingScore: number;
  urlsChecked: number;
  passwordChecks: number;
  date: string;
};

export function generateReportPDF(data: ReportData) {
  // Create a new PDF document
  const doc = new jsPDF();
  
  // Set up fonts and colors
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.setTextColor(40, 40, 40);
  
  // Title
  doc.text("Cyber Safety Assistant", 105, 20, { align: "center" });
  
  doc.setFontSize(16);
  doc.setTextColor(100, 100, 100);
  doc.text("Personalized Safety Report", 105, 30, { align: "center" });
  
  // Date
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(`Generated on: ${data.date}`, 105, 40, { align: "center" });

  // Divider line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 45, 190, 45);

  // Content Sections
  doc.setFontSize(14);
  doc.setTextColor(40, 40, 40);
  doc.setFont("helvetica", "bold");
  doc.text("Your Activity Summary", 20, 60);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  
  const totalInteractions = data.phishingScore + data.urlsChecked + data.passwordChecks;
  
  doc.text(`Total Platform Interactions: ${totalInteractions}`, 25, 70);
  doc.text(`Passwords Analyzed: ${data.passwordChecks}`, 25, 80);
  doc.text(`Suspicious URLs Checked: ${data.urlsChecked}`, 25, 90);
  doc.text(`Phishing Scenarios Completed: ${data.phishingScore}`, 25, 100);

  // Recommendations
  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.text("Security Recommendations", 20, 120);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  
  let yPos = 130;
  
  if (data.passwordChecks < 3) {
    doc.text("- We recommend testing more passwords in the Analyzer to ensure strength.", 25, yPos);
    yPos += 10;
  }
  
  if (data.urlsChecked < 2) {
    doc.text("- Make a habit of checking suspicious URLs before clicking them.", 25, yPos);
    yPos += 10;
  }
  
  if (data.phishingScore < 3) {
    doc.text("- Practice spotting fake emails in the Phishing Simulator.", 25, yPos);
    yPos += 10;
  }
  
  if (totalInteractions > 5) {
    doc.text("- Excellent work! You are actively improving your digital security habits.", 25, yPos);
  }

  // Footer
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Generated by Cyber Safety Assistant", 105, 280, { align: "center" });

  // Save the PDF
  doc.save(`Cyber_Safety_Report_${new Date().toISOString().split('T')[0]}.pdf`);
}
